name: CI/CD Build and deploy

on:
  workflow_dispatch:
      inputs:
        environment:
          type: string
          default: DEV
          required: true


jobs:  
  prod:
    if: ${{ github.event_name == 'push' && github.ref_name == 'master' || github.event.inputs.environment == 'PROD' }}
    env:
      environment: Production

    runs-on: ubuntu-latest
    steps:
      - name: Print value
        run: echo ${{ env.environment }}

      - name: checkout the repository
        uses: actions/checkout@v3
    
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
            dotnet-version: ${{ env.DOTNET_VERSION }}
    
      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
            path: ~/.nuget/packages
            key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
            restore-keys: |
              ${{ runner.os }}-nuget-
    
    
      - name: Build with dotnet
        run: dotnet build ./eShopOnWeb.sln --configuration Release
    
      - name: dotnet publish
        run: dotnet publish ./src/Web/Web.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp
    
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
            name: .net-app
            path: ${{env.DOTNET_ROOT}}/myapp

      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
          path: .net-app
    
      - name: Log into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: Deploy to Azure Web App1
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          resource-group-name: ${{ env.AZURE_RG }}
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: .net-app

        
  dev:
    if: ${{ github.event_name == 'push' && github.ref_name == 'development' || github.event.inputs.environment == 'DEV' }}
    env:
      environment: Development
          
    runs-on: ubuntu-latest
    steps:
        - name: Print value
          run: echo ${{ env.environment }}
          run: echo ${{ env.DOTNET_VERSION }}
  
        - name: checkout the repository
          uses: actions/checkout@v3
      
        - name: Set up .NET Core
          uses: actions/setup-dotnet@v2
          with:
              dotnet-version: ${{ env.DOTNET_VERSION }}
      
        - name: Set up dependency caching for faster builds
          uses: actions/cache@v3
          with:
              path: ~/.nuget/packages
              key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
              restore-keys: |
                ${{ runner.os }}-nuget-
      
      
        - name: Build with dotnet
          run: dotnet build ./eShopOnWeb.sln --configuration Release
      
        - name: dotnet publish
          run: dotnet publish ./src/Web/Web.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp
      
        - name: Upload artifact for deployment job
          uses: actions/upload-artifact@v3
          with:
              name: .net-app
              path: ${{env.DOTNET_ROOT}}/myapp

        - name: Download artifact from build job
          uses: actions/download-artifact@v3
          with:
            name: .net-app
            path: .net-app
      
        - name: Log into Azure
          uses: azure/login@v1
          with:
              creds: ${{ secrets.AZURE_CREDENTIALS }}
      
        - name: Deploy to Azure Web App1
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            resource-group-name: ${{ env.AZURE_RG }}
            app-name: ${{ env.AZURE_WEBAPP_NAME }}
            package: .net-app